//
//  Friend.swift
//  Birthdays
//
//  Created by William MacDonald on 12/11/24.
//

import Foundation
import SwiftData // framework for saving data between launches

@Model // converts Swift class into a stored model managed by SwiftData
class Friend { // instances of a class have a built-in identity that instances of a struct don’t have, SwiftData uses this identity to share its model data across the entire app, to any view that needs it; when any view modifies a model, SwiftData sees those changes immediately
    var name: String
    var birthday: Date // Date type represents a date, down to fractions of a second
    
    // initializer (required by @Model)
    // For structures, Swift generates an initializer with arguments matching each of its properties. But classes don’t get autogenerated initializers, so you need to create one
    init(name: String, birthday: Date) {
        self.name = name
        self.birthday = birthday
    }
    
    // computed property
    var isBirthdayToday: Bool {
        Calendar.current.isDateInToday(birthday) // Calender translates to an absolute point in time (a Date), the .current gets the device's preference
    }
}
